### PR TITLE
⚡️ New trend detection hilbert transform

### LINKED ISSUE #39: Better core `trend` indicator for trend detection
MGM sometimes opens a trade at a peek right before a crash
Trend detection should prevent MGM to open a trade at a peek right before it crashes.

Probably caused by a detection delay.

### PR DESCRIPTION
**Pull request by raftersvk**

### CODE REVIEW

**Comment by raftersvk** [comment]
Hi,

following the first idea of using SAR to improve trend detection I decided to give a go at another indicator :
Hilbert Transform Trend vs Cycle
https://www.tradingpedia.com/videos/trend-vs-cycle-mode-understanding-hilbert-transform/

below is my first test of 800 epoch without ROI and trailing in order to really compare the buy sell impact.

here is a comparison of the best results :
- first we can not see a big difference on total profit
- but average duration seems better for the same kind of profit
image

this is confirmed when looking at epoch with duration less than a day : 
image

detailed files / log here :
[MGM_v012_HTTrend_comparison.zip](https://github.com/Rikj000/MoniGoMani/files/6720739/MGM_v012_HTTrend_comparison.zip)

**Comment by raftersvk** [comment]
there is probably one improvment on this trend detection by avoiding setting the trend which last only one candle as seen below :
image

if anyone can help me do that ;)

**Comment by Rikj000** [comment]
> there is probably one improvement on this trend detection by avoiding setting the trend which last only one candle as seen below 
> if anyone can help me do that ;)

I'm thinking perhaps we could do this particular improvement at a later time! When I implement: https://github.com/Rikj000/MoniGoMani/issues/44
Once the features are in place to make multiple candle usage easy, then we could use our core trend indicator at larger candles, which should yield robuster / slower moving trends. I think that should reduce this issue from occuring :slightly_smiling_face:

**Comment by Rikj000** [comment]
Good spot! :smile: But this will require new tests then! :eyes:

**Comment by raftersvk** [comment]
indeed, so here are the latest results of the night ;)

total profit comparison : SharpeLoss newTrend left / SharpeLoss Vanilla right
image
=> total profit is not so good as first test, but not that far from vanilla either

epochs lasting less than a day : 
image
=> still better result than vanilla, but not as strong as first test

epoch during between 24h and 48h :
image
=> tendency for shorter duration and better result is confirmed here with newTrend

files / log here : 
[MGM_v012_noRoiNoTrail_Sharpe_HTTREND_v2.zip](https://github.com/Rikj000/MoniGoMani/files/6738100/MGM_v012_noRoiNoTrail_Sharpe_HTTREND_v2.zip)

**Comment by raftersvk** [comment]
same analysis with SortinoLoss instead of Sharpe vs Vanilla(Sharpe)

total profit
image
=> still competitive new trend

epochs < 24h
image
=> new trend better and also better than SharpeLoss (not sure what it means or if it only depends of the timerange)

epochs >= 24h < 48h
image

files / log :
[MGM_v012_noRoiNoTrail_Sortino_HTTREND_v2.zip](https://github.com/Rikj000/MoniGoMani/files/6738128/MGM_v012_noRoiNoTrail_Sortino_HTTREND_v2.zip)

**Comment by raftersvk** [comment]
to complete the picture here is a plot of the underlying trend detection :
 - subplot 1 : HT Trend
 - subplot 2 : resulting MGM Trend (-1 = downwards / 0 = sideways / 1 = upwards) 
 - subplot 3 : plusDI / minusDI (to get the direction of the trend)

image

**Comment by raftersvk** [comment]
continuing my research, this is a new plot with the following config :
"trading_during_trends": {
      "buy_trades_when_downwards": false,
      "buy_trades_when_sideways": true,
      "buy_trades_when_upwards": true,
      "sell_trades_when_downwards": true,
      "sell_trades_when_sideways": true,
      "sell_trades_when_upwards": true
    }

on a big picture it looks like we can avoid the big falls, but also miss some of the rebound in the downtrend.
image

[freqtrade-plot-BTC_USDT-1h.zip](https://github.com/Rikj000/MoniGoMani/files/6745548/freqtrade-plot-BTC_USDT-1h.zip)

let's see what we get with different setups ;)

**Comment by Rikj000** [comment]
Merged with: https://github.com/Rikj000/MoniGoMani/pull/79

**Pull request closed without merging**
