### PR TITLE
✨ Export trades from hyperopt/backtest result

### LINKED ISSUE #246: ✨ Implement `mgm-hurry export_trades`
The goal would be to implement PR: https://github.com/Rikj000/MoniGoMani/pull/188 into `mgm-hurry` as `export_trades`

PR has been merged in the [`feature/export-hyperopt-backtest-trades`](https://github.com/Rikj000/MoniGoMani/tree/feature/export-hyperopt-backtest-trades) branch for further development.

### PR DESCRIPTION
**Pull request by raftersvk**

### CODE REVIEW

**Comment by Rikj000** [comment]
@raftersvk could you please add some example result files to help visualize what this PR will do when implemented into `mgm-hurry`? :smile:

**Comment by Rikj000** [comment]
Also for `mgm-hurry` implementation, 
the [`export_csv()`](https://github.com/Rikj000/MoniGoMani/blob/development/mgm-hurry#L1043) function can act as a example/template to implement these new functions :slightly_smiling_face:

**Comment by Rikj000** [comment]
@raftersvk why did you close this PR? :thinking: 
It is still marked as planned?

**Comment by raftersvk** [comment]
sorry mistake while doing some cleanup in my dev branch

**Comment by raftersvk** [comment]
Here is an example of result file with all detailed trades from a given epoch.
It helps understanding where from and when the profit or drawdown occurs instead of having only macro and cumulative indicators.
this is only for "research purposes" and therefore not sure it will benefit to most of the users ;)

[backtest-result-2021-11-12_09-46-24_trades.csv](https://github.com/Rikj000/MoniGoMani/files/7817625/backtest-result-2021-11-12_09-46-24_trades.csv)

**Comment by Rikj000** [comment]
Thank you for re-opening the PR & for uploading the example results file @raftersvk :mechanical_arm: 
I do truly see the usefulness of this feature though,
I think it truly can come in handy to get a deeper comprehension about our test results! :smile:  

However I'll keep this PR a draft until you, me or another collaborator has the time to implement it in `mgm-hurry`

**Comment by Rikj000** [comment]
See PR: https://github.com/Rikj000/MoniGoMani/pull/245

**Pull request closed without merging**
