### PR TITLE
🐞 BugFix - Core trend timeframe not working Dry/Live

### PR DESCRIPTION
**Pull request by taina0407**
Fix the bug that core trend timeframe candles data is not available when running on Dry or Live mode

### CODE REVIEW

**Review by Rikj000 — APPROVED** [review]
Very nice & quick! Truly appreciate this :heart:
Will get to testing right away :slightly_smiling_face:

**Comment by Rikj000** [comment]
@3ylo to test this you should should do the following, I assume these commands are done upon a clean MGM + Freqtrade install:
```powershell
# 1) Change to the monigomani directory
cd ./freqtrade-mgm/monigomani
# 2) Reset the current branch
git reset --hard
# 3) Checkout the development branch
git checkout development
# 4) Pull in the latest changes from the development branch
git pull
# 5) Create & checkout a new local branch based on the latest development to test the PR upon
git checkout -b hotfix/dryrun_core_trend
# 6) Pull in the changes from @taina0407's PR to your local branch
git pull https://github.com/taina0407/MoniGoMani.git hotfix/dryrun_core_trend
```
And then you should be ready for testing :slightly_smiling_face:

**Comment by 3ylo** [comment]
I can confirm that the fixed has worked.Dynamic pairlist with no candles downloaded.
I will leave it running for a while before moving it on my rpi.


image

image

**Comment by Rikj000** [comment]
Same on my end :slightly_smiling_face:
running

**Comment by Rikj000** [comment]
I think 3 confirmations that this has solved the issue is enough!
Let's merge this fix before it confuses too much users :slightly_smiling_face: 
Thank you @3ylo for testing this with us! But mostly thank you @taina0407 for sending in this fix! :heart:

**Pull request merged**
